### ISSUE TITLE
"runc" not found in Pop!_OS 

### ISSUE THREAD

**Issue by PTrottier** [containers/podman.io_old#338] opened 2020-12-23 14:22 UTC
After following the [Ubuntu apt installation instructions](https://github.com/containers/podman.io/blob/master/getting-started/installation.md#ubuntu) on Pop!_OS, when running `podman` (without arguments) or `podman pull path/to/docker`, I am presented with the error:

```
Error: default OCI runtime "runc" not found: invalid argument
```
The solution for me was to also run: `sudo apt install runc`, but it took me a moment to realize it, is this something that can be added to the documentation?

Note: This is an observation from using Pop!_OS, I would have to check if this also applies to Ubuntu and Debian.

Thanks!

**Comment by lsm5** [comment] 2021-01-21 18:22
> After following the [Ubuntu apt installation instructions](https://github.com/containers/podman.io/blob/master/getting-started/installation.md#ubuntu) on Pop!_OS, when running `podman` (without arguments) or `podman pull path/to/docker`, I am presented with the error:
> 
> ```
> Error: default OCI runtime "runc" not found: invalid argument
> ```
> 
> The solution for me was to also run: `sudo apt install runc`, but it took me a moment to realize it, is this something that can be added to the documentation?
> 
> Note: This is an observation from using Pop!_OS, I would have to check if this also applies to Ubuntu and Debian.
> 
> Thanks!

Hi, btw, I'm assuming you followed the instructions for the kubic project repos, yes? If you installed the package from the default pop!_os repos, then it should be reported to the pop!_os or perhaps ubuntu bug tracker site.

**Comment by lsm5** [comment] 2021-01-21 19:09
I'm unable to reproduce this issue on pop os 20.04. Please let me know what version of pop_os and podman are being installed on your system. Also, could you check if your `/usr/share/containers/containers.conf` has this towards the end:

```
[engine.runtimes]
runc = [
        "/usr/lib/cri-o-runc/sbin/runc",
        "/usr/sbin/runc",
        "/usr/bin/runc",
        "/usr/local/bin/runc",
        "/usr/local/sbin/runc",
        "/sbin/runc",
        "/bin/runc",
]
```

The podman package should automatically pull in `cri-o-runc` package which installs runc at `/usr/lib/cri-o-runc/sbin/runc` which is the preferred runc path for podman.

**Comment by lsm5** [comment] 2021-01-21 19:12
I'm gonna close this issue. Please reopen if it still occurs and let me know the details above. Thanks!

**Closed as completed by lsm5** 2021-01-21 19:12 UTC
Labels: packaging, ubuntu, pop-os

**Comment by PTrottier** [comment] 2021-01-21 19:29
> I'm unable to reproduce this issue on pop os 20.04. Please let me know what version of pop_os and podman are being installed on your system.

My apologies, I meant to add that this is on Pop!_OS 20.10 fully up-to-date with the default repos (on a brand new computer).

> Also, could you check if your `/usr/share/containers/containers.conf` has this towards the end:
> 
> ```
> [engine.runtimes]
> runc = [
>         "/usr/lib/cri-o-runc/sbin/runc",
>         "/usr/sbin/runc",
>         "/usr/bin/runc",
>         "/usr/local/bin/runc",
>         "/usr/local/sbin/runc",
>         "/sbin/runc",
>         "/bin/runc",
> ]
> ```
> 
> The podman package should automatically pull in `cri-o-runc` package which installs runc at `/usr/lib/cri-o-runc/sbin/runc` which is the preferred runc path for podman.

This file doesn't exist, I tried adding it and no success either, same error message.

[Edit]

Steps to reproduce:
1. New Pop!_OS 20.10 installation
2. Run `sudo apt-get -y update`
3. Run `sudo apt-get -y install podman`
4. Run `podman` (initial error presented)

**Comment by lsm5** [comment] 2021-01-21 19:33
> > I'm unable to reproduce this issue on pop os 20.04. Please let me know what version of pop_os and podman are being installed on your system.
> 
> My apologies, I meant to add that this is on Pop!_OS 20.10 fully up-to-date with the default repos (on a brand new computer).
> 

If it's default repos and not the Kubic/OBS repos, then those are not owned by this team. Best to file a bug with Pop!_OS.

**Comment by PTrottier** [comment] 2021-01-21 19:34
Fair enough, thanks for your time and investigation @lsm5, take care!
